# Generated by Django 3.2.9 on 2021-11-29 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название похода')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('number_of_persons', models.PositiveIntegerField(default=1, verbose_name='Количество человек')),
                ('number_of_days', models.PositiveIntegerField(default=1, verbose_name='Продолжительность похода')),
                ('calories_per_day', models.PositiveIntegerField(default=2500, verbose_name='Калорий в сутки')),
                ('max_weight', models.PositiveIntegerField(verbose_name='Вес раскладки')),
                ('max_calories', models.PositiveIntegerField(verbose_name='Получено калорий')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название продукта')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('weight', models.PositiveIntegerField(default=100, verbose_name='Порция')),
                ('calories', models.PositiveIntegerField(default=2500, verbose_name='Калорийность в 100г')),
            ],
            options={
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_weight', models.PositiveIntegerField(verbose_name='Вес раскладки')),
                ('max_calories', models.PositiveIntegerField(verbose_name='Получено калорий')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='main.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='main.CartProduct', verbose_name='Продукты'),
        ),
    ]
