# Generated by Django 3.2.9 on 2021-11-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='number_of_persons',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество человек'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='number_of_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Продолжительность похода'),
        ),
    ]
