# Generated by Django 3.2.9 on 2021-11-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211126_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.PositiveIntegerField(default=2500, verbose_name='Калорийность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=100, verbose_name='Вес'),
        ),
    ]
