# Generated by Django 3.2.9 on 2021-11-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211126_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='max_calories',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='max_weight',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='qty',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product_calories',
            field=models.PositiveIntegerField(default=100, verbose_name='Калорийность продукта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product_weight',
            field=models.PositiveIntegerField(default=100, verbose_name='Вес продукта'),
            preserve_default=False,
        ),
    ]
