# Generated by Django 3.2.9 on 2021-11-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211127_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.PositiveIntegerField(default=2500, verbose_name='Калорийность в 100г'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=100, verbose_name='Порция'),
        ),
    ]
